In [2]:
from datetime import datetime, timedelta

start_date = datetime.strptime('2023-07-01', '%Y-%m-%d')

# Constants
num_employees = 6
num_days = 365
base_sequence = ['Morning', 'Morning', 'Afternoon', 'Afternoon', 'Night', 'Night', 'Day off', 'Day off', 'Day off', 'Day off']

# Create a pandas DataFrame to store the roster
roster_data = []
for i in range(num_days):
    # For each day, create a list of shifts for the employees
    day_shifts = base_sequence[i % len(base_sequence):] + base_sequence[:i % len(base_sequence)]
    for j in range(num_employees):
        # Get the shift type for this employee
        shift_type = day_shifts[(j + i) % len(day_shifts)]
        # Add the shift to the roster
        current_date = (start_date + timedelta(days=i)).strftime('%Y-%m-%d')
        roster_data.append([current_date, j, shift_type])

# Create a pandas DataFrame
roster_df = pd.DataFrame(roster_data, columns=['Date', 'Employee', 'Shift'])

# Pivot DataFrame so that employees are columns
roster_pivot_df = roster_df.pivot(index='Date', columns='Employee', values='Shift')

# Write to Excel
roster_pivot_df.to_excel('roster.xlsx')

roster_pivot_df

Employee          0          1          2          3          4          5
Date
0           Morning    Morning  Afternoon  Afternoon      Night      Night
1           Morning    Morning  Afternoon  Afternoon      Night      Night
2         Afternoon  Afternoon      Night      Night    Day off    Day off
3             Night      Night    Day off    Day off  Afternoon  Afternoon
4           Day off    Day off    Day off    Day off      Night      Night
...             ...        ...        ...        ...        ...        ...
360         Morning    Morning  Afternoon  Afternoon      Night      Night
361         Morning    Morning  Afternoon  Afternoon      Night      Night
362       Afternoon  Afternoon      Night      Night    Day off    Day off
363           Night      Night    Day off    Day off  Afternoon  Afternoon
364         Day off    Day off    Day off    Day off      Night      Night

[365 rows x 6 columns]